- name: install mariadb
  apt: 
     name: "{{ item }}"
     state: present
  loop:
    - mariadb-server
    - mariadb-client

- name: update bind address to 0.0.0.0
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify:
    - restart-mariadb

- name: install python3-mysqldb
  apt: 
     name: python3-mysqldb
     state: present
     
- name: create database user
  community.mysql.mysql_user:
    name: "{{ db_username}}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: create a new database with name db_landing_page
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
